@CHCP 1252
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\COPA-CONT1\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\COPA-CONT13\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\COPA-CONT14\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\COPA-CONT15\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\COPA-CONT16\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\COPA-CONT17\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\COPA-CONT18\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\COPA-CONT19\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\COPA-CONT20\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\COPA-CONT21\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\COPA-CONT22\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\COPA-CONT8\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\TIJUCA-COND2\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\TIJUCA-COND4\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\TIJUCA-COND5\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\TIJUCA-DP3\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\TIJUCA-GEREN1\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\TIJUCA-RECEP1\c$\Users\Public\Desktop\ /Y

XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\NITEROI-COMER1\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\NITEROI-COND5\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\NITEROI-COND6\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\NITEROI-COND7\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\NITEROI-COND8\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\NITEROI-CP5\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\NITEROI-CR2\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\NITEROI-DP1\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\NITEROI-GEREN1\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\NITEROI-RECEP1\c$\Users\Public\Desktop\ /Y

XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\CITTA-COMER1\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\CITTA-COND3\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\CITTA-COND4\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\CITTA-COND5\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\CITTA-COND6\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\CITTA-COND7\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\CITTA-CP2\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\CITTA-CP3\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\CITTA-GEREN\c$\Users\Public\Desktop\ /Y
XCOPY "C:\Users\jonathan.rodrigues\Desktop\Sistema de Condomínio.RDP" \\CITTA-RECEP1\c$\Users\Public\Desktop\ /Y


